<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Alexinea.Extensions.Configuration.Toml" />
    <PackageReference Include="NSwag.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Controllers\DotNetNuxt.StarterKit.Controllers.csproj" />
    <ProjectReference Include="..\Data\Postgres\DotNetNuxt.StarterKit.Data.Postgres.csproj" />
    <ProjectReference Include="..\ServiceDefaults\DotNetNuxt.StarterKit.ServiceDefaults.csproj" />
  </ItemGroup>

  <!-- Set assembly version from SolutionVersion -->
  <Target Name="SetSolutionVersion" BeforeTargets="GetAssemblyVersion;GenerateAssemblyInfo">

    <!-- Fallback value -->
    <PropertyGroup>
      <SolutionVersion Condition="'$(SolutionVersion)' == '' and '$(SOLUTION_VERSION)' != ''">$(SOLUTION_VERSION)</SolutionVersion>
      <SolutionVersion Condition="'$(SolutionVersion)' == ''">development</SolutionVersion>
      <InformationalVersion>$(SolutionVersion)</InformationalVersion>
    </PropertyGroup>

    <Message Importance="high" Text="Using SolutionVersion: $(SolutionVersion)" />
  </Target>

</Project>
