<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="NSwag.AspNetCore" Version="14.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Controllers\DotNetNuxt.StarterKit.Controllers.csproj" />
    <ProjectReference Include="..\Data\Postgres\DotNetNuxt.StarterKit.Data.Postgres.csproj" />
  </ItemGroup>

</Project>
